; Convert 2 unpacked HEX digits to equivalent ASCII
; 0-9  -> add 0x30
; A-F  -> add 0x37
;BCD WOULD ONY HAVE 0-9 NOT A-F

	AREA RESET,DATA, READONLY
	EXPORT __Vectors

__Vectors
	DCD 0X10001000;STACK POINTER
	DCD Reset_Handler;RESET VECTOR
	
	ALIGN
	AREA MYCODE,CODE , READONLY
	ENTRY
	EXPORT Reset_Handler

Reset_Handler
	LDR R0,=SRC
	LDR R1,=DEST
	MOV R3 ,#2;
	
L1	LDRB R2,[R0],#1;LOAD LOWER BITS THEN POINTING TO NEXT BYTE
	CMP R2,#0XA; CHECKS IF ALPHABET OR NUMBER
	ADDLO R2,#0X30; NO CARRY BECAUSE EVEN THE LARGEST ADDITION POSSIBLE IN THIS CASE FITS IN 8BITS IE 1BYTE
	ADDHS R2,#0X37;
	STRB R2,[R1],#1;
	SUBS R3,#1;
	BNE L1
	
STOP B STOP
SRC DCD 0x0102; SHOULDNT IT BE 0X000100002
	AREA DATASEG, DATA, READWRITE
DEST DCD 0

	END
		
		