; Write an assembly program to convert a 2 digit hexadecimal number into unpacked ASCII.
; 0-9  -> add 0x30
; A-F  -> add 0x37
;BCD WOULD ONY HAVE 0-9 NOT A-F

	AREA RESET,DATA, READONLY
	EXPORT __Vectors

__Vectors
	DCD 0X10001000;STACK POINTER
	DCD Reset_Handler;RESET VECTOR
	
	ALIGN
	AREA MYCODE,CODE , READONLY
	ENTRY
	EXPORT Reset_Handler

Reset_Handler
	LDR R0,=SRC
	LDR R1,=DEST
	MOV R3 ,#2;
	
	LDRB R2,[R0]; STORES THE VALUE AT SRC
	MOV R4,R2; SPARE
	
L1	AND R2,#0X0F; COPY THE LOWER BYTES
	CMP R2,#0XA
	ADDLO R2,#0X30
	ADDHS R2,#0X37
	STRB R2,[R1],#1; STORE AND THEN INCREMENT BY 1 BYTE
	SUBS R3,#1;
	LSR R2,R4,#4; ROTATE RIGHT
	BNE L1
	
STOP B STOP
SRC DCD 0x12;
	AREA DATASEG, DATA, READWRITE
DEST DCD 0

	END
		
		