	AREA RESET,DATA, READONLY
	EXPORT __Vectors

__Vectors
	DCD 0X10001000 ;stack pointer value when stack is emoty
	DCD Reset_Handler ; reset vector

	ALIGN

	AREA mycode, CODE , READONLY
	ENTRY
	EXPORT Reset_Handler ;till here common
Reset_Handler
	LDR R0,=SRC
	MOV R1,R0
	LDR R2,[R0]
	
	LDR R0,=SRC2
	LDR R3, [R0]
	
	ADD R2,R3
	LDR R4,=SUM
	STR R2,[R4]
	
	
stop 
	b stop
SRC DCD 0x12345678 ;3RD PARAMETER
SRC2 DCD 0X23562356 ;3RD PARAMETER
	AREA mydata , DATA, READWRITE
SUM DCD 0x77777777 
;3RD PARAMETER IS THE DATA BUT, NO USE BCZ RAM ON START ALWAYS INITIALIZES TO 0 THEREFORE 0 IN MEMORY
;CAN INITIALISE RAM WHEN DEBUGGING IN MEMORY WINDOW
	END
	
