;ADDITION OF 2 32BIT NUMBERS
	AREA RESET,DATA, READONLY
	EXPORT __Vectors

__Vectors
	DCD 0X10001000;STACK POINTER
	DCD Reset_Handler;RESET VECTOR
	
	ALIGN
	AREA MYCODE,CODE , READONLY
	ENTRY
	EXPORT Reset_Handler

Reset_Handler
	LDR R0,=SRC1; GETS ADDRESS
	LDR R1,=SRC2
	LDR R2,=SUM
	LDR R3,=CARRY
	
	LDR R4,[R0]; GETS VALUE AT THE ADDRESS
	LDR R5,[R1]
	
	ADDS R6,R4,R5; ADDS THEN UPDATES CARRY
	ADC R7,#0; ADD CARRY TO R3
	
	STR R6,[R2]
	STRB R7,[R3]
	
STOP B STOP
SRC1 DCD 0X12345678
SRC2 DCD 0X87654321
	AREA DATASEG, DATA, READWRITE
SUM DCD 0
CARRY DCB 0

	END